spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/${db.name}
    username: ${db.username}
    password: ${db.password}

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cloud.vault.config: DEBUG
    org.springframework.cloud.vault: DEBUG

management:
  health:
    circuitbreakers:
      enabled: true # 서킷 브레이커 상태를 /actuator/health에 포함
      show-details: always