spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EXIT8
    username: exit8
    password: exit8pass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
